In [1]:
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
%matplotlib.pyplot as ple

torch.manual_seed(2) 

UsageError: Line magic function `%matplotlib.pyplot` not found.


In [3]:
from torch.autograd import Variable

input_data = 4
hidden_data = 3
n_layer =3

lstm = nn.LSTM(input_size= input_data, hidden_size = hidden_data , num_layers =n_layer)

print(lstm)

LSTM(4, 3, num_layers=3)


In [7]:
#make list of 5 , 4 digit input

inputs = [torch.randn(1,input_data) for _ in range(5)]

inputs

[tensor([[ 0.8266, -1.1217,  0.1675,  0.3244]]),
 tensor([[ 0.4140, -0.5388,  0.0123,  0.4103]]),
 tensor([[-1.3550,  0.2929, -1.3609,  0.2702]]),
 tensor([[ 0.0588,  0.3933, -0.2182, -0.5292]]),
 tensor([[-0.2245, -0.4975, -1.4792,  0.7378]])]

In [14]:
h0 = torch.randn(n_layer,1,hidden_data)
c0 = torch.randn(n_layer,1,hidden_data)
#h0 = hidden state
#c0 = memory state

h0 = Variable(h0)
c0 = Variable(c0)

for i in inputs:
    i = Variable(i)
    
    out,hidden = lstm(i.view(1,1,-1),(h0,c0))
    
    print("out:{} with size{}".format(out,out.shape))
    print("hidden",hidden)
    

out:tensor([[[-0.5256, -0.4391,  0.3034]]], grad_fn=<StackBackward>) with sizetorch.Size([1, 1, 3])
hidden (tensor([[[ 0.2528, -0.2185,  0.0890]],

        [[ 0.0090,  0.2047, -0.3298]],

        [[-0.5256, -0.4391,  0.3034]]], grad_fn=<StackBackward>), tensor([[[ 0.3228, -0.4168,  0.2574]],

        [[ 0.0173,  0.3704, -0.5700]],

        [[-0.8373, -0.8197,  0.6668]]], grad_fn=<StackBackward>))
out:tensor([[[-0.5242, -0.4387,  0.3047]]], grad_fn=<StackBackward>) with sizetorch.Size([1, 1, 3])
hidden (tensor([[[ 0.1736, -0.1279,  0.1282]],

        [[ 0.0067,  0.2006, -0.3231]],

        [[-0.5242, -0.4387,  0.3047]]], grad_fn=<StackBackward>), tensor([[[ 0.2304, -0.2617,  0.3055]],

        [[ 0.0128,  0.3701, -0.5597]],

        [[-0.8358, -0.8199,  0.6687]]], grad_fn=<StackBackward>))
out:tensor([[[-0.5219, -0.4386,  0.3065]]], grad_fn=<StackBackward>) with sizetorch.Size([1, 1, 3])
hidden (tensor([[[ 0.1962,  0.0907,  0.3579]],

        [[-0.0269,  0.2073, -0.3016]],

        [[-0

In [15]:
inputs = torch.cat(inputs).view(len(inputs),1,-1)
print(inputs)

tensor([[[ 0.8266, -1.1217,  0.1675,  0.3244]],

        [[ 0.4140, -0.5388,  0.0123,  0.4103]],

        [[-1.3550,  0.2929, -1.3609,  0.2702]],

        [[ 0.0588,  0.3933, -0.2182, -0.5292]],

        [[-0.2245, -0.4975, -1.4792,  0.7378]]])


In [16]:
out,hidden = lstm(inputs,(h0,c0))
print(out)
print(hidden)

tensor([[[-0.5256, -0.4391,  0.3034]],

        [[-0.4761, -0.5087,  0.0755]],

        [[-0.4207, -0.4814, -0.0416]],

        [[-0.3908, -0.4575, -0.1207]],

        [[-0.3737, -0.4392, -0.1677]]], grad_fn=<StackBackward>)
(tensor([[[-0.2533,  0.4384, -0.4539]],

        [[ 0.1059,  0.1768, -0.3990]],

        [[-0.3737, -0.4392, -0.1677]]], grad_fn=<StackBackward>), tensor([[[-0.2888,  0.7787, -0.7211]],

        [[ 0.2212,  0.4414, -0.7037]],

        [[-0.5312, -0.6619, -0.5611]]], grad_fn=<StackBackward>))


### Part of speech


In [18]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import matplotlib.pyplot as plt

%matplotlib inline

In [20]:
training_data=[
    ("The cat ate the cheese".lower().split(),['DET','NN',"V","DET","NN"]),
    ("She read the book".lower().split(),['NN',"V","DET","NN"]),
    ("The dog loves art".lower().split(),['DET','NN','V','NN']),
    ("The elephant answers the phone".lower().split(),['DET','NN','V','DET','NN'])
]
# tuples ma first ko list of words and arko chahi tyo word ko part of speech
#DET = Determinant
#NN = Noun
#V = Verb
word2idx = {}

for sent,tags in training_data:
    for words in sent:
        if words not in word2idx:
            word2idx[words]=len(word2idx)
            
tag2idx= {'DET':0,'NN':1,'V':2}

In [21]:
print(word2idx)

{'the': 0, 'cat': 1, 'ate': 2, 'cheese': 3, 'she': 4, 'read': 5, 'book': 6, 'dog': 7, 'loves': 8, 'art': 9, 'elephant': 10, 'answers': 11, 'phone': 12}


In [22]:
import numpy as np
def prepare_sentence(seq,to_idx):
    idx = [to_idx[w] for w in seq]
    idx = np.array(idx)
    return torch.from_numpy(idx)

In [23]:
example= prepare_sentence("She answers the phone".lower().split(),word2idx)
print(example)

tensor([ 4, 11,  0, 12])


In [35]:
for sent,tag in training_data:
    p=prepare_sentence(tag,tag2idx)
    print(p)

tensor([0, 1, 2, 0, 1])
tensor([1, 2, 0, 1])
tensor([0, 1, 2, 1])
tensor([0, 1, 2, 0, 1])


In [24]:
list = [1,2,3]
array = np.array(list)

In [25]:
array

array([1, 2, 3])

In [30]:
class LSTMTagger(nn.Module):
    def __init__(self,emb_dim,hidden_dim,vocab_size,tagset_size):
        super(LSTMTagger,self).__init__()
        self.hidden_dim = hidden_dim
        
        self.embed = nn.Embedding(vocab_size,emb_dim)
        self.lstm = nn.LSTM(emb_dim,hidden_dim)
        
        self.hidden =self.init_hidden()
        
        self.hidden2tag = nn.Linear(hidden_dim,tagset_size)
    
    def init_hidden(self):
        return(torch.zeros(1,1,self.hidden_dim),torch.zeros(1,1,self.hidden_dim))
    #initially hidden ko value 0 rakhne pachi afai update hunxa
    def forward(self,sentence):
        
        embed = self.embed(sentence)
        lstm_out, self.hidden = self.lstm(embed.view(len(sentence),1,-1),self.hidden)
        
        tag_output = self.hidden2tag(lstm_out.view(len(sentence),-1))
        #return maximum tag with highest value
        tag_scores = F.log_softmax(tag_output,dim=1)
        
        return tag_scores

In [31]:
Embedding_dim = 6
Hidden_dim = 6

model =LSTMTagger(Embedding_dim,Hidden_dim,len(word2idx),len(tag2idx))

print(model)

LSTMTagger(
  (embed): Embedding(13, 6)
  (lstm): LSTM(6, 6)
  (hidden2tag): Linear(in_features=6, out_features=3, bias=True)
)


In [32]:
loss = nn.CrossEntropyLoss()

optimizer = optim.SGD(model.parameters(),lr=0.1)

In [33]:
test_sentence = "The cheese loves elephant".lower().split()

inputs =  prepare_sentence(test_sentence,word2idx)

tag_score = model(inputs)
print(tag_score)


tensor([[-0.7782, -1.3475, -1.2698],
        [-0.7744, -1.3756, -1.2506],
        [-0.8299, -1.2837, -1.2486],
        [-0.8387, -1.2596, -1.2589]], grad_fn=<LogSoftmaxBackward>)


In [34]:
_,prediciton = torch.max(tag_score,dim=1)
print(prediciton)

tensor([0, 0, 0, 0])


In [39]:
epochs = 300 

for epoch in range(epochs):
    
    running_loss = 0.0
    
    for sentence,tags in training_data:
        
        model.zero_grad()
        
        model.hidden = model.init_hidden()
        
        sentence_input = prepare_sentence(sentence,word2idx)
        
        targets = prepare_sentence(tags,tag2idx)
        
        tag_score = model(sentence_input)
        
        losses = loss(tag_score,targets)
        
        running_loss += losses.item()
        
        losses.backward()
        
        optimizer.step()
        
    if(epoch%20 == 19):
        print("Epoch : {}, loss: {}".format(epoch+1,running_loss/len(training_data)))

Epoch : 20, loss: 0.005272059002891183
Epoch : 40, loss: 0.005048574646934867
Epoch : 60, loss: 0.0048420707462355494
Epoch : 80, loss: 0.004650738439522684
Epoch : 100, loss: 0.004473000997677445
Epoch : 120, loss: 0.004307505674660206
Epoch : 140, loss: 0.0041531105525791645
Epoch : 160, loss: 0.004008709860499948
Epoch : 180, loss: 0.0038734471308998764
Epoch : 200, loss: 0.00374646985437721
Epoch : 220, loss: 0.003627113066613674
Epoch : 240, loss: 0.003514674899633974
Epoch : 260, loss: 0.0034086246159859
Epoch : 280, loss: 0.003308426181320101
Epoch : 300, loss: 0.003213647403754294


In [37]:
test_sentence = "The cheese loves elephant".lower().split()

inputs =  prepare_sentence(test_sentence,word2idx)

tag_score = model(inputs)
print(tag_score)

_,prediciton = torch.max(tag_score,dim=1)
print(prediciton)

tensor([[-0.0273, -3.6287, -7.9865],
        [-4.4651, -0.0149, -5.7065],
        [-6.5411, -3.5574, -0.0304],
        [-3.5972, -0.3185, -1.4052]], grad_fn=<LogSoftmaxBackward>)
tensor([0, 1, 2, 1])
